server:
  port: 8082
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:32768/leave_system
    username: root
    password: ji394su3
    schema: classpath:db/schema-dev.sql