server:
  servlet:
    context-path: /leave_system
spring:
  profiles:
    active: @profileActive@
  jackson:
    default-property-inclusion: non_null
logging:
  config: classpath:config/log/logback.xml
  level:
    tw:
      com:
        rex:
          accountbookservice:
            mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
