server:
  port: 8082
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:leave_system
    username: sa
    password: sa
    initialization-mode: embedded
    schema: classpath:db/schema-dev.sql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false