package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.CompanyFax;

public interface CompanyFaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_fax
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String fax);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_fax
     *
     * @mbg.generated
     */
    int insert(CompanyFax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_fax
     *
     * @mbg.generated
     */
    CompanyFax selectByPrimaryKey(String fax);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_fax
     *
     * @mbg.generated
     */
    List<CompanyFax> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_fax
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyFax record);
}