package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.CompanyAddress;

public interface CompanyAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_address
     *
     * @mbg.generated
     */
    int insert(CompanyAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_address
     *
     * @mbg.generated
     */
    CompanyAddress selectByPrimaryKey(String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_address
     *
     * @mbg.generated
     */
    List<CompanyAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyAddress record);
}