package tw.com.rex.leave_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tw.com.rex.leave_system.model.dao.CompanyEmail;

public interface CompanyEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_email
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("email") String email, @Param("companyId") String companyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_email
     *
     * @mbg.generated
     */
    int insert(CompanyEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_email
     *
     * @mbg.generated
     */
    List<CompanyEmail> selectAll();
}