package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.CompanyMobile;

public interface CompanyMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_mobile
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_mobile
     *
     * @mbg.generated
     */
    int insert(CompanyMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_mobile
     *
     * @mbg.generated
     */
    CompanyMobile selectByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_mobile
     *
     * @mbg.generated
     */
    List<CompanyMobile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_mobile
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyMobile record);
}