package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.CompanyPhone;

public interface CompanyPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_phone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_phone
     *
     * @mbg.generated
     */
    int insert(CompanyPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_phone
     *
     * @mbg.generated
     */
    CompanyPhone selectByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_phone
     *
     * @mbg.generated
     */
    List<CompanyPhone> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyPhone record);
}