package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.EmployeeMobile;

public interface EmployeeMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_mobile
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_mobile
     *
     * @mbg.generated
     */
    int insert(EmployeeMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_mobile
     *
     * @mbg.generated
     */
    EmployeeMobile selectByPrimaryKey(String mobile);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_mobile
     *
     * @mbg.generated
     */
    List<EmployeeMobile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_mobile
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeMobile record);
}