package tw.com.rex.leave_system.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tw.com.rex.leave_system.model.dao.EmployeeEmail;

public interface EmployeeEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_email
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("email") String email, @Param("employeeId") String employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_email
     *
     * @mbg.generated
     */
    int insert(EmployeeEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_email
     *
     * @mbg.generated
     */
    List<EmployeeEmail> selectAll();
}