package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.EmployeePhone;

public interface EmployeePhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_phone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_phone
     *
     * @mbg.generated
     */
    int insert(EmployeePhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_phone
     *
     * @mbg.generated
     */
    EmployeePhone selectByPrimaryKey(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_phone
     *
     * @mbg.generated
     */
    List<EmployeePhone> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeePhone record);
}