package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.EmployeeFax;

public interface EmployeeFaxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fax
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String fax);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fax
     *
     * @mbg.generated
     */
    int insert(EmployeeFax record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fax
     *
     * @mbg.generated
     */
    EmployeeFax selectByPrimaryKey(String fax);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fax
     *
     * @mbg.generated
     */
    List<EmployeeFax> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fax
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmployeeFax record);
}