package tw.com.rex.leave_system.mapper;

import java.util.List;
import tw.com.rex.leave_system.model.dao.LeaveHistory;

public interface LeaveHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_history
     *
     * @mbg.generated
     */
    int insert(LeaveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_history
     *
     * @mbg.generated
     */
    LeaveHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_history
     *
     * @mbg.generated
     */
    List<LeaveHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LeaveHistory record);
}