package tw.com.rex.leave_system.model.dao;

import java.util.Date;
import tw.com.rex.leave_system.model.dao.base.BaseDao;

public class Employee extends BaseDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.work_space_id
     *
     * @mbg.generated
     */
    private String workSpaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.manager_id
     *
     * @mbg.generated
     */
    private String managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.arrive_date
     *
     * @mbg.generated
     */
    private Date arriveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.leave_date
     *
     * @mbg.generated
     */
    private Date leaveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password
     *
     * @param password the value for employee.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.company_id
     *
     * @return the value of employee.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.company_id
     *
     * @param companyId the value for employee.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.work_space_id
     *
     * @return the value of employee.work_space_id
     *
     * @mbg.generated
     */
    public String getWorkSpaceId() {
        return workSpaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.work_space_id
     *
     * @param workSpaceId the value for employee.work_space_id
     *
     * @mbg.generated
     */
    public void setWorkSpaceId(String workSpaceId) {
        this.workSpaceId = workSpaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.manager_id
     *
     * @return the value of employee.manager_id
     *
     * @mbg.generated
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.manager_id
     *
     * @param managerId the value for employee.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(String managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.arrive_date
     *
     * @return the value of employee.arrive_date
     *
     * @mbg.generated
     */
    public Date getArriveDate() {
        return arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.arrive_date
     *
     * @param arriveDate the value for employee.arrive_date
     *
     * @mbg.generated
     */
    public void setArriveDate(Date arriveDate) {
        this.arriveDate = arriveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.leave_date
     *
     * @return the value of employee.leave_date
     *
     * @mbg.generated
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.leave_date
     *
     * @param leaveDate the value for employee.leave_date
     *
     * @mbg.generated
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.create_date
     *
     * @return the value of employee.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.create_date
     *
     * @param createDate the value for employee.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.update_date
     *
     * @return the value of employee.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.update_date
     *
     * @param updateDate the value for employee.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}